/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.cardif.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class LineBusiness extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -517663502977028238L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LineBusiness\",\"namespace\":\"com.cardif.avro\",\"fields\":[{\"name\":\"lineBusinessId\",\"type\":\"int\"},{\"name\":\"lineBusinessName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<LineBusiness> ENCODER =
      new BinaryMessageEncoder<LineBusiness>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<LineBusiness> DECODER =
      new BinaryMessageDecoder<LineBusiness>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<LineBusiness> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<LineBusiness> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<LineBusiness> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<LineBusiness>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this LineBusiness to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a LineBusiness from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a LineBusiness instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static LineBusiness fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private int lineBusinessId;
   private java.lang.String lineBusinessName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public LineBusiness() {}

  /**
   * All-args constructor.
   * @param lineBusinessId The new value for lineBusinessId
   * @param lineBusinessName The new value for lineBusinessName
   */
  public LineBusiness(java.lang.Integer lineBusinessId, java.lang.String lineBusinessName) {
    this.lineBusinessId = lineBusinessId;
    this.lineBusinessName = lineBusinessName;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return lineBusinessId;
    case 1: return lineBusinessName;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: lineBusinessId = (java.lang.Integer)value$; break;
    case 1: lineBusinessName = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'lineBusinessId' field.
   * @return The value of the 'lineBusinessId' field.
   */
  public int getLineBusinessId() {
    return lineBusinessId;
  }



  /**
   * Gets the value of the 'lineBusinessName' field.
   * @return The value of the 'lineBusinessName' field.
   */
  public java.lang.String getLineBusinessName() {
    return lineBusinessName;
  }



  /**
   * Creates a new LineBusiness RecordBuilder.
   * @return A new LineBusiness RecordBuilder
   */
  public static com.cardif.avro.LineBusiness.Builder newBuilder() {
    return new com.cardif.avro.LineBusiness.Builder();
  }

  /**
   * Creates a new LineBusiness RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new LineBusiness RecordBuilder
   */
  public static com.cardif.avro.LineBusiness.Builder newBuilder(com.cardif.avro.LineBusiness.Builder other) {
    if (other == null) {
      return new com.cardif.avro.LineBusiness.Builder();
    } else {
      return new com.cardif.avro.LineBusiness.Builder(other);
    }
  }

  /**
   * Creates a new LineBusiness RecordBuilder by copying an existing LineBusiness instance.
   * @param other The existing instance to copy.
   * @return A new LineBusiness RecordBuilder
   */
  public static com.cardif.avro.LineBusiness.Builder newBuilder(com.cardif.avro.LineBusiness other) {
    if (other == null) {
      return new com.cardif.avro.LineBusiness.Builder();
    } else {
      return new com.cardif.avro.LineBusiness.Builder(other);
    }
  }

  /**
   * RecordBuilder for LineBusiness instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LineBusiness>
    implements org.apache.avro.data.RecordBuilder<LineBusiness> {

    private int lineBusinessId;
    private java.lang.String lineBusinessName;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.cardif.avro.LineBusiness.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.lineBusinessId)) {
        this.lineBusinessId = data().deepCopy(fields()[0].schema(), other.lineBusinessId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.lineBusinessName)) {
        this.lineBusinessName = data().deepCopy(fields()[1].schema(), other.lineBusinessName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing LineBusiness instance
     * @param other The existing instance to copy.
     */
    private Builder(com.cardif.avro.LineBusiness other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.lineBusinessId)) {
        this.lineBusinessId = data().deepCopy(fields()[0].schema(), other.lineBusinessId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.lineBusinessName)) {
        this.lineBusinessName = data().deepCopy(fields()[1].schema(), other.lineBusinessName);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'lineBusinessId' field.
      * @return The value.
      */
    public int getLineBusinessId() {
      return lineBusinessId;
    }


    /**
      * Sets the value of the 'lineBusinessId' field.
      * @param value The value of 'lineBusinessId'.
      * @return This builder.
      */
    public com.cardif.avro.LineBusiness.Builder setLineBusinessId(int value) {
      validate(fields()[0], value);
      this.lineBusinessId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'lineBusinessId' field has been set.
      * @return True if the 'lineBusinessId' field has been set, false otherwise.
      */
    public boolean hasLineBusinessId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'lineBusinessId' field.
      * @return This builder.
      */
    public com.cardif.avro.LineBusiness.Builder clearLineBusinessId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'lineBusinessName' field.
      * @return The value.
      */
    public java.lang.String getLineBusinessName() {
      return lineBusinessName;
    }


    /**
      * Sets the value of the 'lineBusinessName' field.
      * @param value The value of 'lineBusinessName'.
      * @return This builder.
      */
    public com.cardif.avro.LineBusiness.Builder setLineBusinessName(java.lang.String value) {
      validate(fields()[1], value);
      this.lineBusinessName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'lineBusinessName' field has been set.
      * @return True if the 'lineBusinessName' field has been set, false otherwise.
      */
    public boolean hasLineBusinessName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'lineBusinessName' field.
      * @return This builder.
      */
    public com.cardif.avro.LineBusiness.Builder clearLineBusinessName() {
      lineBusinessName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public LineBusiness build() {
      try {
        LineBusiness record = new LineBusiness();
        record.lineBusinessId = fieldSetFlags()[0] ? this.lineBusinessId : (java.lang.Integer) defaultValue(fields()[0]);
        record.lineBusinessName = fieldSetFlags()[1] ? this.lineBusinessName : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<LineBusiness>
    WRITER$ = (org.apache.avro.io.DatumWriter<LineBusiness>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<LineBusiness>
    READER$ = (org.apache.avro.io.DatumReader<LineBusiness>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.lineBusinessId);

    out.writeString(this.lineBusinessName);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.lineBusinessId = in.readInt();

      this.lineBusinessName = in.readString();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.lineBusinessId = in.readInt();
          break;

        case 1:
          this.lineBusinessName = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










