/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.cardif.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class MpStatus extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3760604006804501163L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MpStatus\",\"namespace\":\"com.cardif.avro\",\"fields\":[{\"name\":\"status_id\",\"type\":\"int\"},{\"name\":\"status_ds\",\"type\":{\"type\":\"enum\",\"name\":\"Status\",\"symbols\":[\"ATIVO\",\"CANCELADO\",\"NAO_EFETIVADO\",\"EM_NEGOCIACAO\",\"PEND_ATIVACAO\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<MpStatus> ENCODER =
      new BinaryMessageEncoder<MpStatus>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MpStatus> DECODER =
      new BinaryMessageDecoder<MpStatus>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<MpStatus> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<MpStatus> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<MpStatus> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<MpStatus>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this MpStatus to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a MpStatus from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a MpStatus instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static MpStatus fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private int status_id;
   private com.cardif.avro.Status status_ds;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MpStatus() {}

  /**
   * All-args constructor.
   * @param status_id The new value for status_id
   * @param status_ds The new value for status_ds
   */
  public MpStatus(java.lang.Integer status_id, com.cardif.avro.Status status_ds) {
    this.status_id = status_id;
    this.status_ds = status_ds;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return status_id;
    case 1: return status_ds;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: status_id = (java.lang.Integer)value$; break;
    case 1: status_ds = (com.cardif.avro.Status)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'status_id' field.
   * @return The value of the 'status_id' field.
   */
  public int getStatusId() {
    return status_id;
  }



  /**
   * Gets the value of the 'status_ds' field.
   * @return The value of the 'status_ds' field.
   */
  public com.cardif.avro.Status getStatusDs() {
    return status_ds;
  }



  /**
   * Creates a new MpStatus RecordBuilder.
   * @return A new MpStatus RecordBuilder
   */
  public static com.cardif.avro.MpStatus.Builder newBuilder() {
    return new com.cardif.avro.MpStatus.Builder();
  }

  /**
   * Creates a new MpStatus RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MpStatus RecordBuilder
   */
  public static com.cardif.avro.MpStatus.Builder newBuilder(com.cardif.avro.MpStatus.Builder other) {
    if (other == null) {
      return new com.cardif.avro.MpStatus.Builder();
    } else {
      return new com.cardif.avro.MpStatus.Builder(other);
    }
  }

  /**
   * Creates a new MpStatus RecordBuilder by copying an existing MpStatus instance.
   * @param other The existing instance to copy.
   * @return A new MpStatus RecordBuilder
   */
  public static com.cardif.avro.MpStatus.Builder newBuilder(com.cardif.avro.MpStatus other) {
    if (other == null) {
      return new com.cardif.avro.MpStatus.Builder();
    } else {
      return new com.cardif.avro.MpStatus.Builder(other);
    }
  }

  /**
   * RecordBuilder for MpStatus instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MpStatus>
    implements org.apache.avro.data.RecordBuilder<MpStatus> {

    private int status_id;
    private com.cardif.avro.Status status_ds;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.cardif.avro.MpStatus.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.status_id)) {
        this.status_id = data().deepCopy(fields()[0].schema(), other.status_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.status_ds)) {
        this.status_ds = data().deepCopy(fields()[1].schema(), other.status_ds);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing MpStatus instance
     * @param other The existing instance to copy.
     */
    private Builder(com.cardif.avro.MpStatus other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.status_id)) {
        this.status_id = data().deepCopy(fields()[0].schema(), other.status_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.status_ds)) {
        this.status_ds = data().deepCopy(fields()[1].schema(), other.status_ds);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'status_id' field.
      * @return The value.
      */
    public int getStatusId() {
      return status_id;
    }


    /**
      * Sets the value of the 'status_id' field.
      * @param value The value of 'status_id'.
      * @return This builder.
      */
    public com.cardif.avro.MpStatus.Builder setStatusId(int value) {
      validate(fields()[0], value);
      this.status_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'status_id' field has been set.
      * @return True if the 'status_id' field has been set, false otherwise.
      */
    public boolean hasStatusId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'status_id' field.
      * @return This builder.
      */
    public com.cardif.avro.MpStatus.Builder clearStatusId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'status_ds' field.
      * @return The value.
      */
    public com.cardif.avro.Status getStatusDs() {
      return status_ds;
    }


    /**
      * Sets the value of the 'status_ds' field.
      * @param value The value of 'status_ds'.
      * @return This builder.
      */
    public com.cardif.avro.MpStatus.Builder setStatusDs(com.cardif.avro.Status value) {
      validate(fields()[1], value);
      this.status_ds = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'status_ds' field has been set.
      * @return True if the 'status_ds' field has been set, false otherwise.
      */
    public boolean hasStatusDs() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'status_ds' field.
      * @return This builder.
      */
    public com.cardif.avro.MpStatus.Builder clearStatusDs() {
      status_ds = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MpStatus build() {
      try {
        MpStatus record = new MpStatus();
        record.status_id = fieldSetFlags()[0] ? this.status_id : (java.lang.Integer) defaultValue(fields()[0]);
        record.status_ds = fieldSetFlags()[1] ? this.status_ds : (com.cardif.avro.Status) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MpStatus>
    WRITER$ = (org.apache.avro.io.DatumWriter<MpStatus>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MpStatus>
    READER$ = (org.apache.avro.io.DatumReader<MpStatus>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.status_id);

    out.writeEnum(this.status_ds.ordinal());

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.status_id = in.readInt();

      this.status_ds = com.cardif.avro.Status.values()[in.readEnum()];

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.status_id = in.readInt();
          break;

        case 1:
          this.status_ds = com.cardif.avro.Status.values()[in.readEnum()];
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










