/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.cardif.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Ramo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -807991552405602800L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Ramo\",\"namespace\":\"com.cardif.avro\",\"fields\":[{\"name\":\"lob_id\",\"type\":\"int\"},{\"name\":\"lob_ds\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Ramo> ENCODER =
      new BinaryMessageEncoder<Ramo>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Ramo> DECODER =
      new BinaryMessageDecoder<Ramo>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Ramo> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Ramo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Ramo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Ramo>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Ramo to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Ramo from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Ramo instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Ramo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private int lob_id;
   private java.lang.String lob_ds;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Ramo() {}

  /**
   * All-args constructor.
   * @param lob_id The new value for lob_id
   * @param lob_ds The new value for lob_ds
   */
  public Ramo(java.lang.Integer lob_id, java.lang.String lob_ds) {
    this.lob_id = lob_id;
    this.lob_ds = lob_ds;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return lob_id;
    case 1: return lob_ds;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: lob_id = (java.lang.Integer)value$; break;
    case 1: lob_ds = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'lob_id' field.
   * @return The value of the 'lob_id' field.
   */
  public int getLobId() {
    return lob_id;
  }



  /**
   * Gets the value of the 'lob_ds' field.
   * @return The value of the 'lob_ds' field.
   */
  public java.lang.String getLobDs() {
    return lob_ds;
  }



  /**
   * Creates a new Ramo RecordBuilder.
   * @return A new Ramo RecordBuilder
   */
  public static com.cardif.avro.Ramo.Builder newBuilder() {
    return new com.cardif.avro.Ramo.Builder();
  }

  /**
   * Creates a new Ramo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Ramo RecordBuilder
   */
  public static com.cardif.avro.Ramo.Builder newBuilder(com.cardif.avro.Ramo.Builder other) {
    if (other == null) {
      return new com.cardif.avro.Ramo.Builder();
    } else {
      return new com.cardif.avro.Ramo.Builder(other);
    }
  }

  /**
   * Creates a new Ramo RecordBuilder by copying an existing Ramo instance.
   * @param other The existing instance to copy.
   * @return A new Ramo RecordBuilder
   */
  public static com.cardif.avro.Ramo.Builder newBuilder(com.cardif.avro.Ramo other) {
    if (other == null) {
      return new com.cardif.avro.Ramo.Builder();
    } else {
      return new com.cardif.avro.Ramo.Builder(other);
    }
  }

  /**
   * RecordBuilder for Ramo instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Ramo>
    implements org.apache.avro.data.RecordBuilder<Ramo> {

    private int lob_id;
    private java.lang.String lob_ds;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.cardif.avro.Ramo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.lob_id)) {
        this.lob_id = data().deepCopy(fields()[0].schema(), other.lob_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.lob_ds)) {
        this.lob_ds = data().deepCopy(fields()[1].schema(), other.lob_ds);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Ramo instance
     * @param other The existing instance to copy.
     */
    private Builder(com.cardif.avro.Ramo other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.lob_id)) {
        this.lob_id = data().deepCopy(fields()[0].schema(), other.lob_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.lob_ds)) {
        this.lob_ds = data().deepCopy(fields()[1].schema(), other.lob_ds);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'lob_id' field.
      * @return The value.
      */
    public int getLobId() {
      return lob_id;
    }


    /**
      * Sets the value of the 'lob_id' field.
      * @param value The value of 'lob_id'.
      * @return This builder.
      */
    public com.cardif.avro.Ramo.Builder setLobId(int value) {
      validate(fields()[0], value);
      this.lob_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'lob_id' field has been set.
      * @return True if the 'lob_id' field has been set, false otherwise.
      */
    public boolean hasLobId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'lob_id' field.
      * @return This builder.
      */
    public com.cardif.avro.Ramo.Builder clearLobId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'lob_ds' field.
      * @return The value.
      */
    public java.lang.String getLobDs() {
      return lob_ds;
    }


    /**
      * Sets the value of the 'lob_ds' field.
      * @param value The value of 'lob_ds'.
      * @return This builder.
      */
    public com.cardif.avro.Ramo.Builder setLobDs(java.lang.String value) {
      validate(fields()[1], value);
      this.lob_ds = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'lob_ds' field has been set.
      * @return True if the 'lob_ds' field has been set, false otherwise.
      */
    public boolean hasLobDs() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'lob_ds' field.
      * @return This builder.
      */
    public com.cardif.avro.Ramo.Builder clearLobDs() {
      lob_ds = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Ramo build() {
      try {
        Ramo record = new Ramo();
        record.lob_id = fieldSetFlags()[0] ? this.lob_id : (java.lang.Integer) defaultValue(fields()[0]);
        record.lob_ds = fieldSetFlags()[1] ? this.lob_ds : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Ramo>
    WRITER$ = (org.apache.avro.io.DatumWriter<Ramo>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Ramo>
    READER$ = (org.apache.avro.io.DatumReader<Ramo>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.lob_id);

    out.writeString(this.lob_ds);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.lob_id = in.readInt();

      this.lob_ds = in.readString();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.lob_id = in.readInt();
          break;

        case 1:
          this.lob_ds = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










