/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.registry.avro.business;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class BusinessRule extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1611229178940644106L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BusinessRule\",\"namespace\":\"com.registry.avro.business\",\"fields\":[{\"name\":\"role\",\"type\":{\"type\":\"enum\",\"name\":\"Role\",\"symbols\":[\"ADMIN\",\"USER\",\"MANAGER\"]},\"doc\":\"Regra\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<BusinessRule> ENCODER =
      new BinaryMessageEncoder<BusinessRule>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BusinessRule> DECODER =
      new BinaryMessageDecoder<BusinessRule>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<BusinessRule> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<BusinessRule> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<BusinessRule> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<BusinessRule>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this BusinessRule to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a BusinessRule from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a BusinessRule instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static BusinessRule fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Regra */
   private com.registry.avro.business.Role role;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BusinessRule() {}

  /**
   * All-args constructor.
   * @param role Regra
   */
  public BusinessRule(com.registry.avro.business.Role role) {
    this.role = role;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return role;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: role = (com.registry.avro.business.Role)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'role' field.
   * @return Regra
   */
  public com.registry.avro.business.Role getRole() {
    return role;
  }



  /**
   * Creates a new BusinessRule RecordBuilder.
   * @return A new BusinessRule RecordBuilder
   */
  public static com.registry.avro.business.BusinessRule.Builder newBuilder() {
    return new com.registry.avro.business.BusinessRule.Builder();
  }

  /**
   * Creates a new BusinessRule RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BusinessRule RecordBuilder
   */
  public static com.registry.avro.business.BusinessRule.Builder newBuilder(com.registry.avro.business.BusinessRule.Builder other) {
    if (other == null) {
      return new com.registry.avro.business.BusinessRule.Builder();
    } else {
      return new com.registry.avro.business.BusinessRule.Builder(other);
    }
  }

  /**
   * Creates a new BusinessRule RecordBuilder by copying an existing BusinessRule instance.
   * @param other The existing instance to copy.
   * @return A new BusinessRule RecordBuilder
   */
  public static com.registry.avro.business.BusinessRule.Builder newBuilder(com.registry.avro.business.BusinessRule other) {
    if (other == null) {
      return new com.registry.avro.business.BusinessRule.Builder();
    } else {
      return new com.registry.avro.business.BusinessRule.Builder(other);
    }
  }

  /**
   * RecordBuilder for BusinessRule instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BusinessRule>
    implements org.apache.avro.data.RecordBuilder<BusinessRule> {

    /** Regra */
    private com.registry.avro.business.Role role;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.registry.avro.business.BusinessRule.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.role)) {
        this.role = data().deepCopy(fields()[0].schema(), other.role);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing BusinessRule instance
     * @param other The existing instance to copy.
     */
    private Builder(com.registry.avro.business.BusinessRule other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.role)) {
        this.role = data().deepCopy(fields()[0].schema(), other.role);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'role' field.
      * Regra
      * @return The value.
      */
    public com.registry.avro.business.Role getRole() {
      return role;
    }


    /**
      * Sets the value of the 'role' field.
      * Regra
      * @param value The value of 'role'.
      * @return This builder.
      */
    public com.registry.avro.business.BusinessRule.Builder setRole(com.registry.avro.business.Role value) {
      validate(fields()[0], value);
      this.role = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'role' field has been set.
      * Regra
      * @return True if the 'role' field has been set, false otherwise.
      */
    public boolean hasRole() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'role' field.
      * Regra
      * @return This builder.
      */
    public com.registry.avro.business.BusinessRule.Builder clearRole() {
      role = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BusinessRule build() {
      try {
        BusinessRule record = new BusinessRule();
        record.role = fieldSetFlags()[0] ? this.role : (com.registry.avro.business.Role) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BusinessRule>
    WRITER$ = (org.apache.avro.io.DatumWriter<BusinessRule>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BusinessRule>
    READER$ = (org.apache.avro.io.DatumReader<BusinessRule>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeEnum(this.role.ordinal());

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.role = com.registry.avro.business.Role.values()[in.readEnum()];

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.role = com.registry.avro.business.Role.values()[in.readEnum()];
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










