/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.registry.avro.business;
@org.apache.avro.specific.AvroGenerated
public enum Role implements org.apache.avro.generic.GenericEnumSymbol<Role> {
  ADMIN, USER, MANAGER  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Role\",\"namespace\":\"com.registry.avro.business\",\"symbols\":[\"ADMIN\",\"USER\",\"MANAGER\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
